    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name enlighten
    - name: Lint with flake8
      run: |
        conda run -n enlighten conda install flake8
        conda run -n enlighten flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        conda run -n enlighten flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda run -n enlighten conda install pytest
        conda run -n enlighten pytest